server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/task_mgmt_db"
    username: root
    password: 111111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret-key: "ZeaZb1nvXl3B8ifsKr84VuAzJC/N2hq1ettPVDGHhtHtQqudk9JihAAX7c8kwW/s"
  access-token-expiry: 1 #Hours
  refresh-token-expiry: 7 #Days
  token-type: "Bearer"

